services:
  - type: web
    name: ucharbot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromDotEnv: true
      - key: WEBHOOK_URL
        fromDotEnv: true
      - key: CHANNEL_USERNAME
        fromDotEnv: true
